model_list:
  # OPENROUTER MODELS
  - model_name: openai/gpt-oss-20b-or
    litellm_params:
      model: openrouter/openai/gpt-oss-20b:free
      api_key: "os.environ/OPENROUTER_API_KEY"
      rpm: 18
  # GOOGLE GEMINI MODELS
  - model_name: google/gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro
      api_key: "os.environ/GEMINI_API_KEY"
      rpm: 2
      tpm: 125000
      rpd: 50
  - model_name: google/gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: "os.environ/GEMINI_API_KEY"
      rpm: 10
      tpm: 250000
      rpd: 250
  - model_name: google/gemini-2.5-flash-lite
    litellm_params:
      model: gemini/gemini-2.5-flash-lite
      api_key: "os.environ/GEMINI_API_KEY"
      rpm: 15
      tpm: 250000
      rpd: 1000
  - model_name: google/gemini-2.0-flash
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: "os.environ/GEMINI_API_KEY"
      rpm: 15
      tpm: 1000000
      rpd: 200
  - model_name: google/gemini-2.5-flash-tts
    litellm_params:
      model: gemini/gemini-2.5-flash-tts
      api_key: "os.environ/GEMINI_API_KEY"
      rpm: 3
      tpm: 10000
      rpd: 15
  # LM STUDIO MODELS
  - model_name: qwen/qwen3-vl-8b
    litellm_params:
      model: lm_studio/qwen/qwen3-vl-8b
  - model_name: qwen/qwen3-vl-30b
    litellm_params:
      model: lm_studio/qwen/qwen3-vl-30b
  - model_name: qwen/qwen3.5-2b
    litellm_params:
      model: lm_studio/qwen3.5-2b-mlx
  - model_name: qwen/qwen3.5-4b
    litellm_params:
      model: lm_studio/qwen3.5-4b-mlx
  - model_name: qwen/qwen3.5-9b
    litellm_params:
      model: lm_studio/qwen3.5-9b-mlx
  - model_name: qwen/qwen3.5-27b
    litellm_params:
      model: lm_studio/qwen3.5-27b
  - model_name: qwen/qwen3.5-35b-a3b
    litellm_params:
      model: lm_studio/qwen3.5-35b-a3b
  - model_name: openai/gpt-oss-20b
    litellm_params:
      model: lm_studio/openai/gpt-oss-20b
  - model_name: qwen3-embedding
    litellm_params:
      model: lm_studio/text-embedding-qwen3-embedding-0.6b
  # GITHUB MODELS
  - model_name: openai/gpt-4o-mini
    litellm_params:
      model: github/gpt-4o-mini
      api_key: "os.environ/GITHUB_API_KEY"
      rpm: 2
  - model_name: openai/gpt-4.1
    litellm_params:
      model: github/gpt-4.1
      api_key: "os.environ/GITHUB_API_KEY"
      rpm: 2
  - model_name: openai/gpt-4o
    litellm_params:
      model: github/gpt-4o
      api_key: "os.environ/GITHUB_API_KEY"
      rpm: 2
  - model_name: openai/gpt-5-mini
    litellm_params:
      model: github/gpt-5-mini
      api_key: "os.environ/GITHUB_API_KEY"
      rpm: 2
  - model_name: openai/gpt-5
    litellm_params:
      model: github/gpt-5
      api_key: "os.environ/GITHUB_API_KEY"
      rpm: 2
  # GITHUB COPILOT MODELS
  - model_name: openai/gpt-4o-mini
    litellm_params:
      model: github_copilot/gpt-4o-mini-2024-07-18
      rpm: 10
      extra_headers:
        editor-version: "vscode/1.85.1"
        editor-plugin-version: "copilot/1.155.0"
        Copilot-Integration-Id: "vscode-chat"
        user-agent: "GithubCopilot/1.155.0"
  - model_name: openai/gpt-4.1
    litellm_params:
      model: github_copilot/gpt-4.1-2025-04-14
      rpm: 10
      extra_headers:
        editor-version: "vscode/1.85.1"
        editor-plugin-version: "copilot/1.155.0"
        Copilot-Integration-Id: "vscode-chat"
        user-agent: "GithubCopilot/1.155.0"
        Copilot-Vision-Request: "true"
  - model_name: openai/gpt-4o
    litellm_params:
      model: github_copilot/gpt-4o-2024-11-20
      rpm: 10
      extra_headers:
        editor-version: "vscode/1.85.1"
        editor-plugin-version: "copilot/1.155.0"
        Copilot-Integration-Id: "vscode-chat"
        user-agent: "GithubCopilot/1.155.0"
        Copilot-Vision-Request: "true"
  - model_name: openai/gpt-5-mini
    litellm_params:
      model: github_copilot/gpt-5-mini
      rpm: 10
      extra_headers:
        editor-version: "vscode/1.85.1"
        editor-plugin-version: "copilot/1.155.0"
        Copilot-Integration-Id: "vscode-chat"
        user-agent: "GithubCopilot/1.155.0"
        Copilot-Vision-Request: "true"
  - model_name: openai/gpt-5
    litellm_params:
      model: github_copilot/gpt-5
      rpm: 10
      extra_headers:
        editor-version: "vscode/1.85.1"
        editor-plugin-version: "copilot/1.155.0"
        Copilot-Integration-Id: "vscode-chat"
        user-agent: "GithubCopilot/1.155.0"
        Copilot-Vision-Request: "true"
  - model_name: x-ai/grok-code-fast-1
    litellm_params:
      model: github_copilot/grok-code-fast-1
      rpm: 10
      extra_headers:
        editor-version: "vscode/1.85.1"
        editor-plugin-version: "copilot/1.155.0"
        Copilot-Integration-Id: "vscode-chat"
        user-agent: "GithubCopilot/1.155.0"
  - model_name: raptor-mini
    litellm_params:
      model: github_copilot/raptor-mini
      rpm: 10
      extra_headers:
        editor-version: "vscode/1.85.1"
        editor-plugin-version: "copilot/1.155.0"
        Copilot-Integration-Id: "vscode-chat"
        user-agent: "GithubCopilot/1.155.0"
  - model_name: anthropic/claude-sonnet-4.5
    litellm_params:
      model: github_copilot/claude-sonnet-4.5
      rpm: 10
      extra_headers:
        editor-version: "vscode/1.85.1"
        editor-plugin-version: "copilot/1.155.0"
        Copilot-Integration-Id: "vscode-chat"
        user-agent: "GithubCopilot/1.155.0"
        Copilot-Vision-Request: "true"
  - model_name: anthropic/claude-sonnet-4.6
    litellm_params:
      model: github_copilot/claude-sonnet-4.6
      rpm: 10
      extra_headers:
        editor-version: "vscode/1.85.1"
        editor-plugin-version: "copilot/1.155.0"
        Copilot-Integration-Id: "vscode-chat"
        user-agent: "GithubCopilot/1.155.0"
        Copilot-Vision-Request: "true"
  - model_name: anthropic/claude-opus-4.5
    litellm_params:
      model: github_copilot/claude-opus-4.5
      rpm: 3
      extra_headers:
        editor-version: "vscode/1.85.1"
        editor-plugin-version: "copilot/1.155.0"
        Copilot-Integration-Id: "vscode-chat"
        user-agent: "GithubCopilot/1.155.0"
        Copilot-Vision-Request: "true"
  - model_name: anthropic/claude-haiku-4.5
    litellm_params:
      model: github_copilot/claude-haiku-4.5
      rpm: 10
      extra_headers:
        editor-version: "vscode/1.85.1"
        editor-plugin-version: "copilot/1.155.0"
        Copilot-Integration-Id: "vscode-chat"
        user-agent: "GithubCopilot/1.155.0"
        Copilot-Vision-Request: "true"
  - model_name: google/gemini-3-pro-preview
    litellm_params:
      model: github_copilot/gemini-3-pro-preview
      rpm: 10
      extra_headers:
        editor-version: "vscode/1.85.1"
        editor-plugin-version: "copilot/1.155.0"
        Copilot-Integration-Id: "vscode-chat"
        user-agent: "GithubCopilot/1.155.0"
        Copilot-Vision-Request: "true"
  - model_name: google/gemini-3-flash-preview
    litellm_params:
      model: github_copilot/gemini-3-flash-preview
      rpm: 10
      extra_headers:
        editor-version: "vscode/1.85.1"
        editor-plugin-version: "copilot/1.155.0"
        Copilot-Integration-Id: "vscode-chat"
        user-agent: "GithubCopilot/1.155.0"
        Copilot-Vision-Request: "true"
  - model_name: google/gemini-2.5-pro
    litellm_params:
      model: github_copilot/gemini-2.5-pro
      rpm: 10
      extra_headers:
        editor-version: "vscode/1.85.1"
        editor-plugin-version: "copilot/1.155.0"
        Copilot-Integration-Id: "vscode-chat"
        user-agent: "GithubCopilot/1.155.0"
        Copilot-Vision-Request: "true"
  # minimax models
  - model_name: minimax/MiniMax-M2.5
    litellm_params:
      model: minimax/MiniMax-M2.5
      api_key: os.environ/MINIMAX_API_KEY
      api_base: https://api.minimax.io/v1
  - model_name: minimax/MiniMax-M2.7
    litellm_params:
      model: minimax/MiniMax-M2.7
      api_key: os.environ/MINIMAX_API_KEY
      api_base: https://api.minimax.io/v1
  - model_name: minimax/minimax-m2.5
    litellm_params:
      model: minimax/MiniMax-M2.5
      api_key: os.environ/MINIMAX_API_KEY
      api_base: https://api.minimax.io/v1
  - model_name: minimax/MiniMax-M2.5-anthropic
    litellm_params:
      model: minimax/MiniMax-M2.5
      api_key: os.environ/MINIMAX_API_KEY
      api_base: https://api.minimax.io/anthropic/v1/messages
  - model_name: minimax/minimax-m2.7
    litellm_params:
      model: minimax/MiniMax-M2.7
      api_key: os.environ/MINIMAX_API_KEY
      api_base: https://api.minimax.io/v1
  - model_name: minimax/MiniMax-M2.7-anthropic
    litellm_params:
      model: minimax/MiniMax-M2.7
      api_key: os.environ/MINIMAX_API_KEY
      api_base: https://api.minimax.io/anthropic/v1/messages
  # omlx provided models
  # ASR models
  - model_name: omlx/qwen3-asr-0.6b
    litellm_params:
      model: openai/Qwen3-ASR-0.6B
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
    model_info:
      mode: audio_transcription
  - model_name: omlx/qwen3-asr-1.7b
    litellm_params:
      model: openai/Qwen3-ASR-1.7B
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
    model_info:
      mode: audio_transcription
  - model_name: omlx/whisper-large-v3-turbo
    litellm_params:
      model: openai/whisper-large-v3-turbo
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
    model_info:
      mode: audio_transcription
  # TTS models
  - model_name: omlx/qwen3-tts-12hz-1.7b-base
    litellm_params:
      model: openai/Qwen3-TTS-12Hz-1.7B-Base
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
    model_info:
      mode: audio_speech
  - model_name: omlx/qwen3-tts-12hz-1.7b-voicedesign
    litellm_params:
      model: openai/Qwen3-TTS-12Hz-1.7B-VoiceDesign
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
    model_info:
      mode: audio_speech
  - model_name: omlx/qwen3-tts-12hz-1.7b-customvoice
    litellm_params:
      model: openai/Qwen3-TTS-12Hz-1.7B-CustomVoice
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
    model_info:
      mode: audio_speech
  # VL / Chat models
  - model_name: omlx/qwen3-vl-8b
    litellm_params:
      model: openai/Qwen3-VL-8B-Instruct-MLX-4bit
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
  - model_name: omlx/qwen3-vl-30b-a3b
    litellm_params:
      model: openai/Qwen3-VL-30B-A3B-Instruct-MLX-4bit
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
  - model_name: omlx/qwen3.5-2b
    litellm_params:
      model: openai/Qwen3.5-2B-MLX-4bit
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
  - model_name: omlx/qwen3.5-4b
    litellm_params:
      model: openai/Qwen3.5-4B-MLX-4bit
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
  - model_name: omlx/qwen3.5-9b
    litellm_params:
      model: openai/Qwen3.5-9B-MLX-4bit
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
  - model_name: omlx/qwen3.5-27b
    litellm_params:
      model: openai/Qwen3.5-27B-4bit
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
  - model_name: omlx/qwen3.5-27b-distilled
    litellm_params:
      model: openai/Qwen3.5-27B-Claude-4.6-Opus-Distilled-MLX-4bit
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
  - model_name: omlx/qwen3.5-35b-a3b
    litellm_params:
      model: openai/Qwen3.5-35B-A3B-4bit
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
  - model_name: omlx/gpt-oss-20b
    litellm_params:
      model: openai/gpt-oss-20b-MXFP4-Q8
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
  - model_name: omlx/gemma-4-26b-a4b
    litellm_params:
      model: openai/gemma-4-26b-a4b-it-4bit
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
  - model_name: omlx/gemma-4-31b
    litellm_params:
      model: openai/gemma-4-31b-it-4bit
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
  - model_name: omlx/gemma-4-31b-crack
    litellm_params:
      model: openai/Gemma-4-31B-JANG_4M-CRACK
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
  - model_name: omlx/gemma-4-e2b
    litellm_params:
      model: openai/gemma-4-e2b-it-4bit
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
    model_info:
      supports_vision: true
      supports_audio_input: true
  - model_name: omlx/gemma-4-e4b
    litellm_params:
      model: openai/gemma-4-e4b-it-4bit
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
    model_info:
      supports_vision: true
      supports_audio_input: true
  # Special / utility models
  - model_name: omlx/qwen3-forced-aligner-0.6b
    litellm_params:
      model: openai/Qwen3-ForcedAligner-0.6B
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY
  - model_name: omlx/qwen3-tts-tokenizer-12hz
    litellm_params:
      model: openai/Qwen3-TTS-Tokenizer-12Hz
      api_base: os.environ/OMLX_API_BASE
      api_key: os.environ/OMLX_API_KEY

litellm_settings:
  drop_params: true
  success_callback: ["mlflow"]
  failure_callback: ["mlflow"]

general_settings:
  master_key: "os.environ/LITELLM_MASTER_KEY"
  store_model_in_db: true