# 基於官方 MLflow image
FROM ghcr.io/mlflow/mlflow:v3.8.0

# 安裝 PostgreSQL 驅動程式
RUN pip install --no-cache-dir psycopg2-binary

# # 建立 artifacts 目錄
RUN mkdir -p /mlflow/mlruns && chmod -R 777 /mlflow

WORKDIR /mlflow